In [1]:
import numpy as np

In [2]:
def corr(F, I):
    k, l = F.shape  # dimensions of F
    m, n = I.shape  # dimensions of I
    G = np.zeros((m, n))  # Pre-allocating G

    # Dimensions of padded matrix I_pad
    m_pad = m + 2 * (k // 2)
    n_pad = n + 2 * (l // 2)

    # Setting it up
    I_pad = np.zeros((m_pad, n_pad))
    for i in range(m):
        for j in range(n):
            I_pad[(k//2) + i, (l//2) + j] = I[i, j]

    f = np.reshape(F, k * l)  # f vector, as defined in part (ii)

    for i in range(m):
        for j in range(n):
            tij = np.reshape(I_pad[i:i+k, j:j+l], k * l)  # tij, as defined in part (ii)
            G[i, j] = np.dot(f, tij)

    return G

In [15]:
I = np.array([[7,4,1],[8,5,2],[9,6,3]])
F = (1/9)*np.array([[1,1,1],[1,1,1],[1,1,1]])

In [17]:
G = corr(F, I)
print(G)

[[2.66666667 3.         1.33333333]
 [4.33333333 5.         2.33333333]
 [3.11111111 3.66666667 1.77777778]]
